# Generated by Django 6.0 on 2026-01-13 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='일기 내용')),
                ('emotion', models.CharField(blank=True, max_length=50, null=True, verbose_name='감정 상태')),
                ('advice', models.TextField(blank=True, null=True, verbose_name='AI 조언')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diary',
                'ordering': ['-created_at'],
            },
        ),
    ]
