# Generated by Django 6.0 on 2026-01-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='감정 상태'),
        ),
    ]
