# Generated by Django 6.0 on 2026-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_diary_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='첨부 이미지'),
        ),
    ]
